### ISSUE TITLE
求帮助 No virtual method internalCache 

### ISSUE THREAD

**Issue by shirakawa568** [ohmerhe/Kolley#3]
不好意思，我是自学的android 在排错方面不太明白
想问下，下面这个报错什么情况：（）

FATAL EXCEPTION: Thread-7
                                                                            Process: cn.com.jkinfo.bilibilitest, PID: 27544
                                                                            java.lang.NoSuchMethodError: No virtual method internalCache(Lokhttp3/OkHttpClient;)Lokhttp3/internal/InternalCache; in class Lokhttp3/internal/Internal; or its super classes (declaration of 'okhttp3.internal.Internal' appears in /data/app/cn.com.jkinfo.test-2/split_lib_dependencies_apk.apk)
                                                                                at okhttp3.internal.huc.HttpURLConnectionImpl.newHttpEngine(HttpURLConnectionImpl.java:392)
                                                                                at okhttp3.internal.huc.HttpURLConnectionImpl.initHttpEngine(HttpURLConnectionImpl.java:343)
                                                                                at okhttp3.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:126)
                                                                                at okhttp3.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:263)
                                                                                at com.android.volley.toolbox.HurlStack.addBodyIfExists(HurlStack.java:264)
                                                                                at com.android.volley.toolbox.HurlStack.setConnectionParametersForRequest(HurlStack.java:234)
                                                                                at com.android.volley.toolbox.HurlStack.performRequest(HurlStack.java:107)
                                                                                at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:96)
                                                                                at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:112)

使用是参考示例的，应该没错吧：
package cn.com.jkinfo.test

import android.support.v7.app.AppCompatActivity
import android.os.Bundle
import android.os.Parcel
import android.os.Parcelable
import android.util.Log
import com.ohmerhe.kolley.request.Http
import java.nio.charset.Charset

class BuildActivity : AppCompatActivity(),Parcelable {

    var name : String = ""

    val CREATOR: Parcelable.Creator<BuildActivity> = object : Parcelable.Creator<BuildActivity> {
        override fun createFromParcel(source: Parcel): BuildActivity {
            var ba : BuildActivity = BuildActivity()
            ba.name=source.readString()
            return BuildActivity()
        }

        override fun newArray(size: Int): Array<BuildActivity> {
            TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
        }
    }

    override fun writeToParcel(dest: Parcel?, flags: Int) {
        //TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
    }

    override fun describeContents(): Int {
        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_build)

        Http.init(this)

        Http.post{
            url = "http://10.10.10.103:3001/api/post"
            raw = "{\"id\":\"1\"}"

            onSuccess {
                log("on success ${it.toString(Charset.defaultCharset())}")
            }
            onFail { error ->
                log("on fail ${error.toString()}")
            }
        }
    }
    fun log(text: String) {
        Log.d("BuildActivity", text)
    }
}

**Comment by ohmerhe** [comment]
你这是测试代码吗？
